SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `MusicStore`.`Orders` 
DROP FOREIGN KEY `fk_Orders_Album1`,
DROP FOREIGN KEY `fk_Orders_Composition1`;

ALTER TABLE `MusicStore`.`Orders` 
DROP COLUMN `Composition_idComposition`,
CHANGE COLUMN `Album_idAlbum` `Album_idAlbum` INT(11) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`idOrders`, `Users_idUsers`, `Album_idAlbum`),
DROP INDEX `fk_Orders_Composition1_idx` ;

ALTER TABLE `MusicStore`.`Orders` 
ADD CONSTRAINT `fk_Orders_Album1`
  FOREIGN KEY (`Album_idAlbum`)
  REFERENCES `MusicStore`.`Album` (`idAlbum`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
